### Cadastrar Usuário
# @name register user
POST http://localhost:8989/api/users/register
Content-Type: application/json

{
  "name": "Juliane Maran",
  "username": "juhmaran@email.com",
  "password": "9o6P!ab3",
  "phoneNumber": "+5511998765432"
}

