### Cadastrar novo quarto
# @name cadastrar quarto
POST http://localhost:8888/api/hotel/bedrooms/register
Content-Type: application/json

{
  "number": "101",
  "roomType": "SOLTEIRO",
  "capacity": 1,
  "dailyRate": 120.50,
  "description": "Quarto individual com vista para a cidade.",
  "available": true,
  "hotelId": 1
}
