### Cadastrar novo quarto
# @name registerBedroom
POST http://localhost:8585/api/v1/bedrooms/register
Content-Type: application/json

{
  "number": "308",
  "room_type": "SINGLE",
  "capacity": 1,
  "daily_rate": 110.00,
  "description": "Quarto de solteiro com vista para a cidade.",
  "available": false,
  "hotel_id": 1
}

### Cadastrar novo quarto
# @name updateBedroomById
PUT http://localhost:8585/api/v1/bedrooms/2
Content-Type: application/json

{
  "number": "103",
  "room_type": "FAMILY",
  "capacity": 3,
  "daily_rate": 150.00,
  "description": "Quarto de casal com vista para o jardim.",
  "available": false,
  "hotel_id": 1
}

### Buscar Hotel por ID
# @name Buscar quarto por ID
GET http://localhost:8585/api/v1/bedrooms/4

### Listar todos os quartos
# @name listBedrooms
GET http://localhost:8585/api/v1/bedrooms/list

### Excluir Hotel por ID
# @name deleteBedroomById
DELETE http://localhost:8585/api/v1/bedrooms/5

### Listar quartos do Hotel ID
# @name getBedroomsByHotelId
GET http://localhost:8585/api/v1/bedrooms/2/hotels
