### Cadastrar novo Hotel
# @name registerHotel
POST http://localhost:8585/api/v1/hotels/register
Content-Type: application/json

{
  "hotel_name": "Hotel Aconchego",
  "location": "Rua Dias Gomes, São Paulo - SP",
  "phone_number": "+11987654321",
  "email": "contato@hotelnaconchego.com",
  "hotel_type": "HOTEL",
  "cnpj_number": "01040428000120",
  "description": "Hotel com piscina, sauna e restaurante.",
  "room_count": 100
}

### Atualizar dados do Hotel por ID
# @name updateHotelById
PUT http://localhost:8585/api/v1/hotels/1
Content-Type: application/json

{
  "hotel_name": "Hotel Aconchego",
  "location": "Rua Dias Gomes, São Paulo - SP",
  "phone_number": "+11987654321",
  "email": "contato@hotelnaconchego.com",
  "hotel_type": "RESORT",
  "description": "Hotel com piscina, sauna e restaurante.",
  "room_count": 100
}

### Buscar Hotel por ID
# @name getHotelById
GET http://localhost:8585/api/v1/hotels/{id}

### Listar todos os hotéis
# @name LlistHotel
GET http://localhost:8585/api/v1/hotels/list

### Excluir Hotel por ID
# @name deleteHotelById
DELETE http://localhost:8585/api/v1/hotels/{id}

### Buscar Hotel por ID
# @name getHotelByIdWithBedroomIds
GET http://localhost:8585/api/v1/hotels/1/bedrooms




