### Cadastrar novo Hotel
# @name Cadastrar novo Hotel
POST http://localhost:8888/api/hotel/hotels/create
Content-Type: application/json

{
  "hotelName": "Hotel Aconchego",
  "location": "Rua Dias Gomes, São Paulo - SP",
  "phoneNumber": "+11987654321",
  "email": "contato@hotelnaconchego.com",
  "hotelType": "HOTEL",
  "cnpjNumber": "01040428000120",
  "description": "Exemplo Descrição",
  "roomCount": 10
}

### Atualizar dados do Hotel por ID
# @name Atualizar dados do Hotel
PUT http://localhost:8888/api/hotel/hotels/{id}
Content-Type: application/json

{
  "hotelName": "Hotel Aconchego",
  "location": "Rua Dias Gomes, São Paulo - SP",
  "phoneNumber": "+11987654321",
  "email": "contato@hotelnaconchego.com",
  "hotelType": "RESORT",
  "description": "Exemplo Descrição",
  "roomCount": 10
}

### Buscar Hotel por ID
# @name Buscar Hotel por ID
GET http://localhost:8888/api/hotel/hotels/{id}

### Listar todos os hotéis
# @name Listar todos os hotéis
GET http://localhost:8888/api/hotel/hotels/list

### Excluir Hotel por ID
# @name Excluir Hotel
DELETE http://localhost:8888/api/hotel/hotels/{id}





