server:
  port: 8585
  servlet:
    context-path: /api/v1

spring:
  application:
    name: book-now
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/booknow_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  # Internacionalização (MessageSourceAutoConfiguration)
  messages:
    basename: messages # arquivo de mensagens base
    encoding: UTF-8 # Codificação dos arquivos de mensagens
    fallback-to-system-locale: true # Usar idioma do sistema se não encontrar tradução
    always-use-message-format: true # Aplicar regras do MessageFormat
  # Jackson (JacksonProperties)
  jackson:
    date-format: "dd/MM/yyyy HH:mm:ss" # Formato de data e hora padrão
    locale: pt-BR # Localidade para formatação
    time-zone: America/Sao_Paulo # Fuso horário padrão
    serialization-inclusion: non_null # Incluir apenas propriedades não nulas na serialização
    property-naming-strategy: SNAKE_CASE # Usar nomes de chaves em snake_case

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: DEBUG
