server:
  port: 8585
  servlet:
    context-path: /api/v1

spring:
  application:
    name: book-now
  devtools:
    add-properties: true
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  # MySQL Database Connection Properties
  datasource:
    url: jdbc:mysql://localhost:3306/book_now_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update

# Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    operations-sorter: alpha
    path: /documentation.html

logging:
  level:
    web: DEBUG
