server:
  port: 8585
  servlet:
    context-path: /api/v1

spring:
  application:
    name: book-now
  devtools:
    add-properties: true
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  # MySQL Database Connection Properties
  datasource:
    url: jdbc:mysql://localhost:3306/booknow_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin

# http://localhost:8585/api/v1/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
#  api-docs:
#    version: OPENAPI_3_1
#    path: /api-docs # /api-docs endpoint custom path
#  default-consumes-media-type: application/json
#  default-produces-media-type: /

logging:
  level:
    web: DEBUG
