server:
  port: 8585
  servlet:
    context-path: /api/v1

spring:
  application:
    name: book-now
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/booknow_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: DEBUG
