server:
  port: 8888
  servlet:
    context-path: /api/hotel

spring:
  application:
    name: book-now
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/book_now_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
#  docker:
#    compose:
#      enable: true # Se o suporte do docker compose está habilitado.
#      file: '' # Caminho para um arquivo de configuração específico do Docker Compose.
#      host: '' # Nome do host ou IP da máquina onde os contêineres do Docker são iniciados.
#      lifecycle-management: start-and-stop # Docker compõe o gerenciamento do ciclo de vida.
#      profiles:
#        active: '' # Docker compõe perfis que devem estar ativos.
#      skip:
#        in-tests: true # Se deve pular os testes.
#      start:
#        log-level: info # Nível de log para saída.
logging:
  level:
    web: DEBUG